### ISSUE TITLE
No JSON parsing

### ISSUE THREAD

**Issue by asomov** [zauberlabs/gnip4j#15]
Hi all,
I wonder if this use case is covered by the current API. 
We need to connect to GNIP to get data. The data will be stored in a document NoSQL database. Which means that we do not what to spend the time on parsing the JSON document into the Activity instance. But we would like to re-use the connection and monitoring facilities from this library. 
Are you interested in such a use case ?

Cheers,
Andrey

**Comment by michaelahlers** [comment]
:+1:
