### ISSUE TITLE
the stream url has changed

### ISSUE THREAD

**Issue by nicolastribal** [zauberlabs/gnip4j#25]
the current configuration to the stream url has changed, from https://stream.gnip.com:443/accounts/xxxxxxx/publishers/twitter/streams/track/xxxxxx.json   to https://stream.gnip.com:443/accounts/xxxxxxx/publishers/twitter/streams/usertrack/xxxxxx.json, the url must be set in order to prevent this bug.

**Comment by sfat** [comment]
I don't think this is true. [GET /track/:stream](http://support.gnip.com/apis/powertrack/api_reference.html#Stream)

**Comment by jbcazaux** [comment]
usertrack is another stream. It allows to add 3M rules like 
from:username
mention:username
retweets_of:username
