### ISSUE TITLE
Error Deleting Arabic Rule

### ISSUE THREAD

**Issue by brew42** [zauberlabs/gnip4j#31]
Hi

I am getting an issue deleting an Arabic rule I have added to gnip.

The rule is created fine on gnip and can view in edit console
(االخلافة على منهج النبوة )  ((الخلافة على منهاج النبوة ) OR (الخلافة على منهج النبوة ))

However, looking at readonly gnip view it displays differently
{"value":"(Ø§Ø§Ù„Ø®Ù„Ø§ÙØ© Ø¹Ù„Ù‰ Ù…Ù†Ù‡Ø¬ Ø§Ù„Ù†Ø¨ÙˆØ© )  ((Ø§Ù„Ø®Ù„Ø§ÙØ© Ø¹Ù„Ù‰ Ù…Ù†Ù‡Ø§Ø¬ Ø§Ù„Ù†Ø¨ÙˆØ© ) OR (Ø§Ù„Ø®Ù„Ø§ÙØ© Ø¹Ù„Ù‰ Ù…Ù†Ù‡Ø¬ Ø§Ù„Ù†Ø¨ÙˆØ© ))","tag":"26974_266"}

Then when I call gnip.delete it fails to delete the rule and doesn't throw an error.
Calling getRules again confirms the rule is found and still on gnip

Regards
Tom

**Comment by jcodagnone** [comment]
Were you using master at that time or version 1.1.1?

I think this was covered at https://github.com/zauberlabs/gnip4j/commit/5e986d28b30942f1bbb3d42c59ccefba5407b57c

Version 2.0.0 is available.
