### ISSUE TITLE
Upgrade to Gnip 2.0 API

### ISSUE THREAD

**Issue by chaitut715** [zauberlabs/gnip4j#45]
It is not certainly an issue. 
I am forced to create issue as I am not aware how to contact with you/team.

I would like to whether you have any plans to upgrade this library to support Gnip 2.0 API

**Comment by jcodagnone** [comment]
Hi, if you review the last commits you wil see that master contains multiple pull requests to support Gnip version 2. I think master is almost release ready

**Comment by chaitut715** [comment]
Thank you @jcodagnone .
