### ISSUE TITLE
PowerTrack V2 Stream/Rules Base URL

### ISSUE THREAD

**Issue by jmmk** [zauberlabs/gnip4j#50]
The API Reference: http://support.gnip.com/apis/powertrack2.0/api_reference.html#Stream shows the following:

Stream URL: `https://gnip-stream.twitter.com/...`
Rules URL: `https://gnip-api.twitter.com...`

But `PowerTrackV2UriStrategy.java` uses:

```java
public static final String DEFAULT_STREAM_URL_BASE  = "https://stream-data-api.twitter.com";
public static final String DEFAULT_RULE_URL_BASE = "https://data-api.twitter.com";
```

Are they both valid? Is the latter one deprecated?

**Comment by jcodagnone** [comment]
Hi, I remember that gnip-api.twitter.com didn't work during the beta. I've updated the rule hostname as it works. 
I still need to check the stream hostname.

**Comment by jcodagnone** [comment]
I've been testing changing  `DEFAULT_STREAM_URL_BASE  = "https://stream-data-api.twitter.com";` to `gnip-stream.twitter.com` as stated at http://support.gnip.com/apis/powertrack2.0/api_reference.html#Stream  but get a connection with my account (502 errors). I'm leaving for now as is.

**Comment by jmmk** [comment]
@jcodagnone I'll test it as well in the next few days and see what happens.

I commented on your commit, but I'll repeat here: the URL you changed contains an extra `/` which breaks the HTTP request

**Comment by jcodagnone** [comment]
@jmmk typo fixed at ad2c414ac6

**Comment by jmmk** [comment]
Both domains seem to work fine for me using curl and gnip4j. I asked Gnip support about all the different urls, and this was the reply:

> - For your real-time stream please use the gnip-stream.twitter.com domain.
> - For the Rules API use the gnip-api.twitter.com domain.
> - For Replay use the gnip-stream.gnip.com domain.
>
> These are not expected to change, and no promises on support for the old ones you cited.

Where "old ones" means those mentioned above: `stream-data-api.twitter.com` and `data-api.twitter.com`

**Comment by jcodagnone** [comment]
Cool, I made some extra tests with a new stream (outside powertrack 2 beta) and worked all fine. I updated the hostname at 0a818290

**Comment by jmmk** [comment]
👍  thanks
