### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by dennislloydjr** [zauberlabs/gnip4j#53]
Are there any plans to publish a new Maven release? It would be really helpful to get the latest from the repository instead of building the project and having just this one library that we have to track differently.

**Comment by jcodagnone** [comment]
https://github.com/zauberlabs/gnip4j/releases/tag/2.0.0
http://search.maven.org/#artifactdetails%7Ccom.zaubersoftware.gnip4j%7Cgnip4j-core%7C2.0.0%7Cjar
