### ISSUE TITLE
Matching rules doesn't have the ID field

### ISSUE THREAD

**Issue by eblanco90** [zauberlabs/gnip4j#64]
Hello,

In the new GNIP 2.0, the field matching_rules now has the fields "tag" and "id". However, this change is not implemented in the class "MatchingRules" since there is only "tag" and "value" (old version).

We should add a field in this class called "id" (and maintain the "value" one for compatibility).

Thanks.

**Comment by jcodagnone** [comment]
You are right. Fixed!

**Comment by eblanco90** [comment]
Hello, I think this should be too  in the class "MatchingRules", that's the class we use to get the ID. Thanks.

**Comment by jcodagnone** [comment]
Right! https://github.com/zauberlabs/gnip4j/commit/299a22bc0cc60ec54b65022ef64534e1b090ca32
